name: TeleportPlugin
version: '${project.version}'
main: me.lodaris.teleportplugin.TeleportPlugin
api-version: '1.16'
commands:
  tpa:
    description: Отправить запрос на телепортацию другому игроку
    usage: /tpa <игрок>
  tpaccept:
    description: Принять запрос на телепортацию
    usage: /tpaccept